name: Tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
    - run: pnpm run install
    - run: pnpm run lint
    - run: pnpm run test
